apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
data:
  # ALLOWED_ORIGINS: "http://localhost:3000,http://34.42.12.23,http://34.42.12.23:80"  # Use service name for internal communication
  ALLOWED_ORIGINS: "*"
