apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  REACT_APP_USER_SERVICE_URL: "http://34.70.153.27:8001"           # user-service external IP
  REACT_APP_TRANSACTION_SERVICE_URL: "http://34.44.91.100:8002"    # transaction-service external IP
  REACT_APP_NOTIFICATION_SERVICE_URL: "http://34.44.222.17:8003"   # notification-service external IP
