apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: gcr.io/devops-demo-440509/user-service:latest
        ports:
        - containerPort: 8000  # Internal container port
        env:
        - name: ALLOWED_ORIGINS
          value: "http://localhost:3000,http://34.42.12.23"  # Add the LoadBalancer IP
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
  - port: 8001          # External port within the cluster
    targetPort: 8000     # Internal container port
