name: Deploy 3-Tier Finance App

on:
  push:
    branches:
      - test  

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Kubernetes CLI
        run: |
          echo "${KUBECONFIG_FILE}" | base64 -d > "$HOME/.kube/config"
          chmod 600 "$HOME/.kube/config"

      - name: Apply Kubernetes ConfigMaps
        run: |
          kubectl apply -f k8s_manifests/notification-service-configmap.yaml
          kubectl apply -f k8s_manifests/transaction-service-configmap.yaml
          kubectl apply -f k8s_manifests/user-service-configmap.yaml

      - name: Apply Kubernetes Deployments
        run: |
          kubectl apply -f k8s_manifests/frontend-deployment.yml
          kubectl apply -f k8s_manifests/notification-service-deployment.yml
          kubectl apply -f k8s_manifests/transaction-service-deployment.yml
          kubectl apply -f k8s_manifests/user-service-deployment.yml

      - name: Verify Deployment Status
        run: |
          kubectl rollout status deployment frontend-deployment
          kubectl rollout status deployment notification-service-deployment
          kubectl rollout status deployment transaction-service-deployment
          kubectl rollout status deployment user-service-deployment

  monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy Prometheus for Monitoring
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install prometheus prometheus-community/kube-prometheus-stack

      - name: Deploy Grafana for Visualization
        run: |
          kubectl apply -f https://raw.githubusercontent.com/grafana/helm-charts/main/charts/grafana/templates/grafana-namespace.yaml
          helm repo add grafana https://grafana.github.io/helm-charts
          helm install grafana grafana/grafana --namespace grafana

      - name: Get Grafana Admin Password
        run: |
          kubectl get secret --namespace grafana grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
