name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GCP Container Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Build Docker Images
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/notification-service:latest ./notification-service
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/transaction-service:latest ./transaction-service
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-service:latest ./user-service
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest ./frontend

    - name: Push Docker Images
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/notification-service:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/transaction-service:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-service:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest
